monedas = {
    "MXN": ['pesos', 'centavos'],
    "AFN": ['afganis', 'pul'],
    "ALL": ['leks', 'qindarka'],
    "DZD": ['dinares argelinos', 'céntimos'],
    "USD": ['dólares estadounidenses', 'centavos'],
    "EUR": ['euros', 'céntimos'],
    "AOA": ['kwanzas', 'céntimos'],
    "XCD": ['dólares del Caribe Oriental', 'centavos'],
    "ARS": ['pesos argentinos', 'centavos'],
    "AMD": ['drams armenios', 'lumas'],
    "AWG": ['florines arubeños', 'centavos'],
    "AUD": ['dólares australianos', 'centavos'],
    "AZN": ['manat azerbaiyanos', 'gəpiks'],
    "BSD": ['dólares bahameños', 'centavos'],
    "BHD": ['dinares bahreiníes', 'fils'],
    "BDT": ['taka', 'poishas'],
    "BBD": ['dólares de Barbados', 'centavos'],
    "BYN": ['rublos bielorrusos', 'kapeikas'],
    "BZD": ['dólares beliceños', 'centavos'],
    "XOF": ['francos CFA de África Occidental', 'céntimos'],
    "BMD": ['dólares bermudeños', 'centavos'],
    "BTN": ['ngultrum', 'chetrums'],
    "BOB": ['pesos bolivianos', 'centavos'],
    "BOV": ['Mvdol', 'centavos'],
    "BAM": ['marcos convertibles', 'feninges'],
    "BWP": ['pulas', 'thebe'],
    "NOK": ['coronas noruegas', 'øre'],
    "BRL": ['reales brasileños', 'centavos'],
    "BND": ['dólares de Brunéi', 'centavos'],
    "BGN": ['leva búlgaros', 'stotinki'],
    "BIF": ['francos burundeses', 'céntimos'],
    "CVE": ['escudos caboverdianos', 'centavos'],
    "KHR": ['rieles camboyanos', 'sens'],
    "XAF": ['francos CFA de África Central', 'céntimos'],
    "CAD": ['dólares canadienses', 'centavos'],
    "KYD": ['dólares de las Islas Caimán', 'centavos'],
    "CLP": ['pesos chilenos', 'centavos'],
    "CLF": ['unidades de fomento', ''],
    "CNY": ['yuanes chinos', 'jiaos'],
    "COP": ['pesos colombianos', 'centavos'],
    "COU": ['unidades de valor real', ''],
    "KMF": ['francos comorenses', 'céntimos'],
    "CDF": ['francos congoleños', 'céntimos'],
    "NZD": ['dólares neozelandeses', 'centavos'],
    "CRC": ['colones costarricenses', 'céntimos'],
    "HRK": ['kunas croatas', 'lipas'],
    "CUP": ['pesos cubanos', 'centavos'],
    "CUC": ['pesos convertibles cubanos', 'centavos'],
    "ANG": ['florines de las Antillas Neerlandesas', 'centavos'],
    "CZK": ['coronas checas', 'haléřes'],
    "DKK": ['coronas danesas', 'øre'],
    "DJF": ['francos yibutianos', 'céntimos'],
    "DOP": ['pesos dominicanos', 'centavos'],
    "EGP": ['libras egipcias', 'piastres'],
    "SVC": ['colones salvadoreños', 'centavos'],
    "ERN": ['nakfas', 'centavos'],
    "SZL": ['lilangenis', 'centavos'],
    "ETB": ['birrs etíopes', 'santims'],
    "FKP": ['libras de las Islas Malvinas', 'centavos'],
    "FJD": ['dólares fiyianos', 'centavos'],
    "XPF": ['francos CFP', 'céntimos'],
    "GMD": ['dalasis', 'bututs'],
    "GEL": ['laris georgianos', 'tetris'],
    "GHS": ['cedis ghaneses', 'pesewas'],
    "GIP": ['libras de Gibraltar', 'peniques'],
    "DKK": ['coronas danesas', 'øre'],
    "XCD": ['dólares del Caribe Oriental', 'centavos'],
    "EUR": ['euros', 'céntimos'],
    "USD": ['dólares estadounidenses', 'centavos'],
    "GTQ": ['quetzales', 'centavos'],
    "GBP": ['libras esterlinas', 'peniques'],
    "GNF": ['francos guineanos', 'céntimos'],
    "XOF": ['francos CFA de África Occidental', 'céntimos'],
    "GYD": ['dólares guyaneses', 'centavos'],
    "HTG": ['gourdes', 'céntimos'],
    "USD": ['dólares estadounidenses', 'centavos'],
    "AUD": ['dólares australianos', 'centavos'],
    "EUR": ['euros', 'céntimos'],
    "HNL": ['lempiras', 'centavos'],
    "HKD": ['dólares de Hong Kong', 'centavos'],
    "HUF": ['forintos húngaros', 'filléres'],
    "ISK": ['coronas islandesas', 'aurar'],
    "INR": ['rupias indias', 'paise'],
    "IDR": ['rupias indonesias', 'senes'],
    "XDR": ['derechos especiales de giro', ''],
    "IRR": ['riales iraníes', ''],
    "IQD": ['dinares iraquíes', 'fils'],
    "EUR": ['euros', 'céntimos'],
}


def obtener_moneda(clave_moneda):
    clave_moneda = clave_moneda.upper()

    moneda = monedas[clave_moneda][0]
    return moneda


def obtener_centavos(clave_moneda):
    clave_moneda = clave_moneda.upper()

    centavos = monedas[clave_moneda][1]
    return centavos

    